[package]
name = "rust_os"
version = "1.0.0"
authors = ["Rstar284"]
edition = "2018"

[dependencies]
bootloader = "0.9"
volatile = "0.2.6"
spin = "0.9.2"
x86_64 = "0.14"
pic8259 = "0.10.2"
pc-keyboard = "0.5.1"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
